
title: 'worldpotato.github.io'
description: "My little blog about my developers life"
baseurl: ""
url: "https://worldpotato.github.io"

header_pages:
  - index.md
  - about.md
  - gpgkey.md

style: dark

footer: 'follow me on <a href="https://twitch.com/w0rldpotato">twitch</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
